const thaiLetters = [
  ["ก","ก ไก่","g/k","middle","ไก่","chicken"],
  ["ข","ข ไข่","kh","high","ไข่","egg"],
  ["ฃ","ฃ ขวด","kh","high","ขวด","bottle - obsolete letter"],
  ["ค","ค ควาย","kh","low","ควาย","buffalo"],
  ["ฅ","ฅ คน","kh","low","คน","person - obsolete letter"],
  ["ฆ","ฆ ระฆัง","kh","low","ระฆัง","bell"],
  ["ง","ง งู","ng","low","งาน","work"],
  ["จ","จ จาน","j","middle","จ่าย","pay"],
  ["ฉ","ฉ ฉิ่ง","ch","high","ฉัน","I - female"],
  ["ช","ช ช้าง","ch","low","ชื่อ","name"],
  ["ซ","ซ โซ่","s","low","ซ่อม","repair"],
  ["ฌ","ฌ เฌอ","ch","low","เฌอ","tree"],
  ["ญ","ญ หญิง","y","low","หญิง","woman"],
  ["ฎ","ฎ ชฎา","d","middle","ชฎา","headdress"],
  ["ฏ","ฏ ปฏัก","dt","middle","ปฏัก","goad"],
  ["ฐ","ฐ ฐาน","th","high","ฐาน","base"],
  ["ฑ","ฑ มณโฑ","th","low","มณโฑ","Montho"],
  ["ฒ","ฒ ผู้เฒ่า","th","low","ผู้เฒ่า","elder"],
  ["ณ","ณ เณร","n","low","เณร","novice monk"],
  ["ด","ด เด็ก","d","middle","ดู","look"],
  ["ต","ต เต่า","dt","middle","ต้อง","must / need"],
  ["ถ","ถ ถุง","th","high","ถ่าย","shoot / photograph"],
  ["ท","ท ทหาร","th","low","ทำ","do"],
  ["ธ","ธ ธง","th","low","ธุรกิจ","business"],
  ["น","น หนู","n","low","นุ่น","Noon"],
  ["บ","บ ใบไม้","b","middle","บริษัท","company"],
  ["ป","ป ปลา","bp","middle","ไป","go"],
  ["ผ","ผ ผึ้ง","ph","high","ผม","I - male"],
  ["ฝ","ฝ ฝา","f","high","ฝ่าย","department / side"],
  ["พ","พ พาน","ph","low","พร้อม","ready"],
  ["ฟ","ฟ ฟัน","f","low","ไฟ","light / electricity"],
  ["ภ","ภ สำเภา","ph","low","ภาษี","tax"],
  ["ม","ม ม้า","m","low","ไหม","question particle"],
  ["ย","ย ยักษ์","y","low","ยัง","still / yet"],
  ["ร","ร เรือ","r","low","เรา","we"],
  ["ล","ล ลิง","l","low","ล่าสุด","latest"],
  ["ว","ว แหวน","w","low","วัน","day"],
  ["ศ","ศ ศาลา","s","high","ศุกร์","Friday"],
  ["ษ","ษ ฤๅษี","s","high","ภาษา","language"],
  ["ส","ส เสือ","s","high","สรุป","summary"],
  ["ห","ห หีบ","h","high","ให้","give / for"],
  ["ฬ","ฬ จุฬา","l","low","กีฬา","sport"],
  ["อ","อ อ่าง","ʔ / vowel carrier","middle","อะไร","what"],
  ["ฮ","ฮ นกฮูก","h","low","ฮัลโหล","hello"]
];

const thaiVowels = [
  ["ะ / ั","a","short","กัน","together"],
  ["า","aa","long","งาน","work"],
  ["ิ","i","short","คิด","think"],
  ["ี","ii","long","ดี","good"],
  ["ึ","ʉ","short","ถึง","to / until"],
  ["ื","ʉʉ","long","ชื่อ","name"],
  ["ุ","u","short","คุณ","you / polite title"],
  ["ู","uu","long","ดู","look"],
  ["เ-ะ / เ-็","e","short","เช็ก","check"],
  ["เ-","ee","long","เทค","take"],
  ["แ-ะ / แ-็","ɛ","short","และ","and"],
  ["แ-","ɛɛ","long","แก้","fix"],
  ["โ-ะ","o","short","คน","person"],
  ["โ-","oo","long","โอน","transfer"],
  ["เ-าะ","ɔ","short","เพราะ","because"],
  ["-อ","ɔɔ","long","ขอ","ask / request"],
  ["เ-อะ","ə","short","เจอ","meet / find"],
  ["เ-อ","əə","long","เงิน","money"],
  ["เ-ีย","ia","long","เปลี่ยน","change"],
  ["เ-ือ","ʉa","long","เรื่อง","matter"],
  ["-ัว","ua","long","ตัวอย่าง","example"],
  ["ไ- / ใ-","ai","diphthong","ไหม","question"],
  ["เ-า","ao","diphthong","เรา","we"],
  ["-ำ","am","am","ทำ","do"]
];

const readingDrills = [
  {label:"Word", thai:"งาน", chunks:"ง + า + น", meaning:"work", note:"ง starts with ng. า is long aa. Final น = n."},
  {label:"Word", thai:"ต้อง", chunks:"ต + ้ + อ + ง", meaning:"must / need", note:"A word you use constantly: เราต้อง... = we need to..."},
  {label:"Word", thai:"ทำ", chunks:"ท + ำ", meaning:"do / make", note:"Notice ำ gives the -am sound."},
  {label:"Word", thai:"อะไร", chunks:"อ + ะ + ไ + ร", meaning:"what", note:"High-frequency question word."},
  {label:"Word", thai:"บ้าง", chunks:"บ + ้ + า + ง", meaning:"some / what things", note:"Useful in อะไรบ้าง = what things / what all."},
  {label:"Phrase", thai:"เราต้องทำอะไรบ้างครับ", chunks:"เรา | ต้อง | ทำ | อะไร | บ้าง | ครับ", meaning:"What do we need to do?", note:"Read a sentence you already know how to say."},
  {label:"Phrase", thai:"เดี๋ยวผมเช็กก่อนครับ", chunks:"เดี๋ยว | ผม | เช็ก | ก่อน | ครับ", meaning:"Let me check first.", note:"Recognition before speed."},
  {label:"Phrase", thai:"อันนี้ไม่ตรงครับ", chunks:"อันนี้ | ไม่ | ตรง | ครับ", meaning:"This doesn’t match.", note:"Useful for numbers, versions, and documents."},
  {label:"Phrase", thai:"ช่วยเช็กอันนี้ให้ผมหน่อยครับ", chunks:"ช่วย | เช็ก | อันนี้ | ให้ | ผม | หน่อย | ครับ", meaning:"Check this for me.", note:"A recurring request structure."},
  {label:"Phrase", thai:"เรื่องนี้แก้ยังไงครับ", chunks:"เรื่องนี้ | แก้ | ยังไง | ครับ", meaning:"How do we resolve this?", note:"A phrase that sounds like you."}
];